name: movie_success_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas=2.0.3
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - jupyter=1.0.0
  - jupyterlab=4.0.3
  - notebook=6.5.4
  - ipykernel=6.25.0
  - ipython=8.14.0
  - plotly=5.15.0
  - dash=2.11.0
  - dash-bootstrap-components=1.4.1
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - black=23.7.0
  - flake8=6.0.0
  - yaml=0.2.5
  - pip
  - pip:
    - python-dotenv==1.0.0
    - joblib==1.3.1
    - statsmodels==0.14.0
    - pyyaml==6.0
    - openpyxl==3.1.2
    - tqdm==4.65.0
    - nbformat==5.9.2